config/routes.rb
Whattoplay::Application.routes.draw do
  post '/auth/:provider/callback' => 'sessions#create'
  get '/auth/failure' => 'sessions#failure'
  get '/signout' => 'sessions#destroy', as: :signout
  get '/signin' => 'sessions#new', as: :signin
  post '/' => 'steam#find_games', as: :find_games
  get '/privacy' => 'steam#privacy', as: :privacy

  root to: 'steam#index'
end

app/models/steam_app.rb
class SteamApp
  include Mongoid::Document
  include Mongoid::Attributes::Dynamic
  validates :steam_appid, uniqueness: true
  
  field :type 
  field :steam_appid
  field :categories
  field :header_image
  field :name
end

app/models/user.rb
class User
  include Mongoid::Document
  field :steam_id, type: String
  field :remember_token, type: String

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end
  private 
  
  def create_remember_token
    self.remember_token = User.encrypt(User.new_remember_token)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include SessionsHelper
  require 'steam_api'
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_filter :verify_authenticity_token, only: :create

  def new
  end

  def create
    session[:steam_info]= {}
    session[:steam_info][:uid] = request.env['omniauth.auth'][:uid]
    session[:steam_info][:info] = request.env['omniauth.auth'][:info]

    user = User.find_or_create_by(steam_id: session[:steam_info][:uid])
    login user
    redirect_back_or root_url
  end

  def failure
    redirect_to root_url, :alert => "Authentication error: #{params[:message].humanize}"
  end

  def destroy
    logout 
    redirect_to root_url
  end
end

app/controllers/steam_controller.rb
class SteamController < ApplicationController
  before_action :authenticate_user!, only: [:find_games, :index]
  before_action :set_stuff, only: [:index]

  def index
  end

  def find_games
    users = [] 
    users += params[:friends] unless params[:friends].nil?
    users << current_user.steam_id
    @games = SteamApi.find_coop_games(users, params[:categories]).sort_by {|g| g.name} 
    @owned_games = SteamApi.get_owned_games(current_user.steam_id).map{|a| {a.delete("appid") => a}}.inject(:merge)

    respond_to do |format|
      format.js { render 'find_games', :locals => {:owned_games => @owned_games}}
      format.html { render 'index'}
      format.json {}
    end
  end

  def privacy
  end

  private 
  def set_stuff
    @friend_list ||= SteamApi.get_friend_list(current_user.steam_id) 
    @friends ||= SteamApi.get_friend_summaries(@friend_list.map{|f| f["steamid"]})
    @categories ||= SteamApp.pluck(:categories).flatten.uniq.map{|c| [c["description"], c["id"]]}
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def login(user)
    remember_token = User.new_remember_token
    cookies[:remember_token] = {
      :value => remember_token,
      :expires => 1.day.from_now
    }
    user.update_attribute(:remember_token, User.encrypt(remember_token))
    self.current_user = user
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token = User.encrypt(cookies[:remember_token])
    begin
      @current_user ||= User.find_by(remember_token: remember_token)
    rescue Mongoid::Errors::DocumentNotFound
      nil
    end
  end

  def current_user?(user)
    user == current_user
  end

  def user_signed_in?
    !current_user.nil?
  end
  
  def authenticate_user!
    unless user_signed_in?
      store_location
      redirect_to signin_url
    end
  end

  def logout
    self.current_user = nil
    cookies.delete(:remember_token)
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url
  end
end

app/helpers/steam_helper.rb
module SteamHelper
end

app/views/layouts/_footer.html.erb
<%= link_to "Powered by Steam", "http://steampowered.com" %> | This site is and was never affiliated with Valve or Steam | <%= link_to "Privacy", privacy_path %>

app/views/layouts/_head.html.erb
  <div class="contain-to-grid">
    <nav class="top-bar">
      <ul class="title-area">
        <li class="name"><h1><%= link_to "WhatToPlay", root_path %></h1></li>
      </ul>

      <div class="top-bar-section">
        <ul class="right">
          <% if user_signed_in? %>
          <li> <img src="<%= session[:steam_info][:info][:image] %>"> </li>
          <li> <%= link_to session[:steam_info][:info][:nickname], session[:steam_info][:info][:urls][:Profile] %> </li>
          <li> <%= link_to 'Sign out', signout_path %> </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
<head>
 <meta charset="utf-8" />

 <!-- Uncomment to make IE8 render like IE7 -->
 <!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

 <!-- Set the viewport width to device width for mobile -->
 <meta name="viewport" content="width=device-width, initial-scale=1.0" />

 <title>What to play?</title>

 <%= stylesheet_link_tag    "application" %>
 <%= javascript_include_tag "vendor/custom.modernizr" %>
 <%= csrf_meta_tags %>
</head>

<body>
  <%= render 'layouts/head' %>

  <section id="content">
    <%= yield %>
  </section>

<hr>
  <section id="footer">
    <%= render 'layouts/footer' %>
  </section>

  <%= javascript_include_tag "application" %>
</body>
</html>

app/views/steam/_form.html.erb
<%= form_tag find_games_path, remote: true, method: :post do |f| %>
<div class="row collapse">
  <div class="large-1 columns">
    <span class="prefix">Users</span>
  </div>
  <div class="large-4 columns">
    <%= select_tag("friends",options_for_select(@friends.map{|f| [f["personaname"],f["steamid"]]}.sort), multiple: true, class: "select")%>
  </div>
  <div class="large-1 columns">
    <span class="prefix">Categories</span>
  </div>
  <div class="large-4 columns">
    <%= select_tag("categories",options_for_select(@categories), multiple: true, class: "select") %>
  </div>
  <div class="large-2 columns">
    <%= submit_tag "Go", class: "button postfix", data: {disable_with: "Searching..."}, width: "100%" %>
  </div>
</div>
<% end %>

app/views/steam/fetch_games.js.erb
$("#ajax_feedback_text").text("<%= "#{@count_diff} new games fetched" %>")

app/views/steam/find_games.html.erb
<%= render @games %>

app/views/steam/find_games.js.erb
$("#ajax_result").empty()
$("#ajax_result").append("<%= escape_javascript(render(:partial => "steam_apps/steam_app", :collection => @games, :locals => {:owned_games => @owned_games})) %>");
// history.pushState(null, null, '<%= request.fullpath %>')

app/views/steam/index.html.erb
<section>
    <%= render 'form' %>
</section>

<section>
<h3 class="text-center">Games</h3>
  <ul id="ajax_result" class="text-center">
  </ul>
</section>

app/views/steam/privacy.html.erb
The data used here is public data coming from the <%= link_to "Steam Web Api", "http://steampowered.com"%>.
No user-data is stored.

app/views/steam_apps/_steam_app.html.erb
<li><%= link_to(image_tag(SteamApi.get_app_image_url(steam_app.steam_appid, owned_games[steam_app.steam_appid]["img_logo_url"]), class: "game_image"), "http://store.steampowered.com/app/#{steam_app.steam_appid}") %></li>